<?php
/**
 * Created by PhpStorm.
 * User: Peace
 * Date: 11/25/2017
 * Time: 7:37 PM
 */

namespace v1;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'v1\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}