<?php
/**
 * Created by PhpStorm.
 * User: Peace
 * Date: 11/17/2017
 * Time: 9:25 PM
 */

namespace restful\component;

use yii\rest\ActiveController;

class ApiController extends ActiveController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

//    public function beforeAction($action)
//    {
//        return parent::beforeAction($action); // TODO: Change the autogenerated stub
//    }

//    public function afterAction($action, $result)
//    {
//        return parent::afterAction($action, $result);
////         返回数据结构合法性检查
////        if ($result === null || $result[0] === null || $result[0][0] === null || $result[0][1] === null || $result[1] === null || !is_array($result[1]))
////            return json_encode(['code' => 1, 'message' => '返回数据结构错误', 'contents' => [], 'more' => false]);
////
////        // $result说明：基本结构如下 [['code', 'message'], 'contents'(, 'more')]
////        if (isset($result[2]))
////            return json_encode(['code' => $result[0][0], 'message' => $result[0][1], 'contents' => $result[1], 'more' => $result[2]]);
////        else
////            return json_encode(['code' => $result[0][0], 'message' => $result[0][1], 'contents' => $result[1], 'more' => false]);
//    }

}