<?php
/**
 * Created by PhpStorm.
 * User: Peace
 * Date: 11/17/2017
 * Time: 9:25 PM
 */

namespace restful\component;

use yii\rest\ActiveController;

class ApiController extends ActiveController
{
    public $phpInput = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub

        $phpInput = file_get_contents('php://input', 'r');
        if ($phpInput) $this->phpInput = json_decode($phpInput, true);
        return true;
    }

    public function afterAction($action, $result)
    {
        parent::afterAction($action, $result);

//         返回数据结构合法性检查
        if ($result == false || !is_array($result) ||  !is_array($result[0]) || !is_numeric($result[0][0]) || $result[0][1] === null ||  !is_array($result[1]) || !is_bool($result[2]))
            $data = ['code' => ReturnCode::$data_1[0], 'message' => ReturnCode::$data_1[1], 'contents' => [], 'more' => false];
        // $result说明：基本结构如下 [['code', 'message'], 'contents', 'more']
        else
            $data = ['code' => $result[0][0], 'message' => $result[0][1], 'contents' => $result[1], 'more' => $result[2]];

        return json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

}