<?php
/**
 * Created by PhpStorm.
 * User: Peace
 * Date: 11/17/2017
 * Time: 9:27 PM
 */

namespace restful\component;

use yii\web\Controller;

class ApiH5Controller extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}